### ISSUE TITLE
Значки для гугловских приложений

### ISSUE THREAD

**Issue by alice-mkh** [BeYkeRYkt/Holo-Theme#1]
Здравствуйте. Не нашел вашу почту, поэтому пишу сюда. Если я добавлю в тему значки для приложений вроде гуглокарт и прочих (вытащенные из старых версий), это с лицензионной точки зрения нормально? По идее, не очень, но я видел темы, где они используются, а у вас сейчас значков очень мало.

**Comment by BeYkeRYkt** [comment]
Здравствуйте. Я не особо силен в лицензиях, но наверно нормально)
